mlflow:
  experiment_name: "fraud_detection_"
  registered_model_name: "fraud_detection_xgboost"
  tracking_uri: "http://mlflow-server:5500"
  artifact_location: "s3://mlflow/fraud_detection"
  s3_endpoint_url: "http://minio:9000"
  bucket: "mlflow"

kafka:
  bootstrap_servers: "pkc-ld537.ca-central-1.aws.confluent.cloud:9092"
  username: "VAWD3ORVNJTGIOBA"
  password: "YjrlsQeZmoaPCLIvyyoE0dMohu8OulNMOz3rxgDG/LvVlYCUlKohmLceshBl0SjH"
  topic: "transactions"
  output_topic: "fraud_predictions"
  timeout: 600000

# features: 

model:
  test_size: 0.2
  seed: 42 # makes sure model is constant 
  params:
    n_estimators: 300
    learning_rate: 0.05
    max_depth: 5
    subsample: 0.8
    colsample_bytree: 0.8
    scale_pos_weight: 1
    tree_method: 'hist'
  path: "/app/models/fraud_detection_model.pkl"

# spark:
